version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-container
    networks:
      - monitor
    ports:
      - "80:80"

  monitor:
    build: 
      context: ./monitor_server
      dockerfile: Dockerfile
    container_name: monitor-container
    networks:
      - monitor
    depends_on:
      - web-server
    volumes:
      - $PWD:/usr/src/app
    entrypoint: ["/bin/bash", "/mcheck_server_status.sh"]

networks:
  monitor:
    driver: bridge
