version: '3.8'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-container
    networks:
      - monitor
    ports:
      - "80:80"

  monitor:
    build: ./monitor_server
    container_name: monitor-container
    networks:
      - monitor
    ports:
      - "8080:80"
    depends_on:
      - web-server
    volumes:
      - ./monitor_server:/usr/src/app

networks:
  monitor:
    driver: bridge
